### ISSUE TITLE
when starting the alfresco

### ISSUE THREAD

**Issue by jasonmamy** [aborroy/alfresco-genai#2]
After cloning the repository (on Linux system) I comment out the ai and gen-ai sections in the `compose.yml` file (just to start up alfresco), the contents of my `compose.yml` file are:

```
include:
#  - genai-stack/compose.yaml
  - alfresco/compose.yaml
#  - alfresco/compose-ai.yaml
```

I then start up the stack:

`docker compose up`

I see many errors (seemingly permissions errors):

```
solr6-1               | Caused by: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /opt/alfresco-search-services/data/alfresco
solr6-1               |         at org.apache.solr.core.SolrCore.initSnapshotMetaDataManager(SolrCore.java:486)
solr6-1               |         at org.apache.solr.core.SolrCore.<init>(SolrCore.java:917)
solr6-1               |         ... 19 more
solr6-1               | Caused by: java.nio.file.AccessDeniedException: /opt/alfresco-search-services/data/alfresco
```

What would be causing these errors? Seems like something in the `alfresco/compose.yml` file, I'm just not sure what?

Thanks

**Comment by aborroy** [comment]
You need to apply some permissions to local folders when using this project in Linux: https://github.com/alfresco/alfresco-docker-installer?tab=readme-ov-file#docker-volumes

You may also change to standard Docker Volumes instead of bind volumes.
